export { default as CartPage } from './cart/cart';
export { default as CatalogPage } from './catalog/catalog';
export { default as FavoritesPage } from './favorites/favorites';
export { default as HomePage } from './home/home';
export { default as ProfilePage } from './profile/profile';
export { default as SignInPage } from './signin/signin';
export { default as SignUpPage } from './signup/signup';
export { default as NotFoundPage } from './not-found/not-found';
export { default as Checkout } from './checkout/checkout';